// Single source of truth for the country list shared by BMS, SEQ and APP.
//
// Ordering contract: BRAZIL, MEXICO, UNITED STATES first, then every other
// country alphabetically (by English name, locale-pinned for determinism).
//
// Storage contract: all apps persist the ISO code (e.g. "BR"). Use
// COUNTRY_BY_ISO for display and STATES_BY_ISO for the dependent state select.

export type ZipProvider = "viacep" | "zippopotam"

export type Country = {
  name: string
  iso: string
  zipProvider?: ZipProvider
  states?: { code: string; name: string }[]
}

/** Raw catalogue. Order here is irrelevant — COUNTRIES below imposes the canonical order. */
const RAW_COUNTRIES: Country[] = [
  {
    name: "Brazil",
    iso: "BR",
    zipProvider: "viacep",
    states: [
      { code: "AC", name: "Acre" },
      { code: "AL", name: "Alagoas" },
      { code: "AP", name: "Amapá" },
      { code: "AM", name: "Amazonas" },
      { code: "BA", name: "Bahia" },
      { code: "CE", name: "Ceará" },
      { code: "DF", name: "Distrito Federal" },
      { code: "ES", name: "Espírito Santo" },
      { code: "GO", name: "Goiás" },
      { code: "MA", name: "Maranhão" },
      { code: "MT", name: "Mato Grosso" },
      { code: "MS", name: "Mato Grosso do Sul" },
      { code: "MG", name: "Minas Gerais" },
      { code: "PA", name: "Pará" },
      { code: "PB", name: "Paraíba" },
      { code: "PR", name: "Paraná" },
      { code: "PE", name: "Pernambuco" },
      { code: "PI", name: "Piauí" },
      { code: "RJ", name: "Rio de Janeiro" },
      { code: "RN", name: "Rio Grande do Norte" },
      { code: "RS", name: "Rio Grande do Sul" },
      { code: "RO", name: "Rondônia" },
      { code: "RR", name: "Roraima" },
      { code: "SC", name: "Santa Catarina" },
      { code: "SP", name: "São Paulo" },
      { code: "SE", name: "Sergipe" },
      { code: "TO", name: "Tocantins" },
    ],
  },
  {
    name: "United States",
    iso: "US",
    zipProvider: "zippopotam",
    states: [
      { code: "AL", name: "Alabama" },
      { code: "AK", name: "Alaska" },
      { code: "AZ", name: "Arizona" },
      { code: "AR", name: "Arkansas" },
      { code: "CA", name: "California" },
      { code: "CO", name: "Colorado" },
      { code: "CT", name: "Connecticut" },
      { code: "DE", name: "Delaware" },
      { code: "FL", name: "Florida" },
      { code: "GA", name: "Georgia" },
      { code: "HI", name: "Hawaii" },
      { code: "ID", name: "Idaho" },
      { code: "IL", name: "Illinois" },
      { code: "IN", name: "Indiana" },
      { code: "IA", name: "Iowa" },
      { code: "KS", name: "Kansas" },
      { code: "KY", name: "Kentucky" },
      { code: "LA", name: "Louisiana" },
      { code: "ME", name: "Maine" },
      { code: "MD", name: "Maryland" },
      { code: "MA", name: "Massachusetts" },
      { code: "MI", name: "Michigan" },
      { code: "MN", name: "Minnesota" },
      { code: "MS", name: "Mississippi" },
      { code: "MO", name: "Missouri" },
      { code: "MT", name: "Montana" },
      { code: "NE", name: "Nebraska" },
      { code: "NV", name: "Nevada" },
      { code: "NH", name: "New Hampshire" },
      { code: "NJ", name: "New Jersey" },
      { code: "NM", name: "New Mexico" },
      { code: "NY", name: "New York" },
      { code: "NC", name: "North Carolina" },
      { code: "ND", name: "North Dakota" },
      { code: "OH", name: "Ohio" },
      { code: "OK", name: "Oklahoma" },
      { code: "OR", name: "Oregon" },
      { code: "PA", name: "Pennsylvania" },
      { code: "RI", name: "Rhode Island" },
      { code: "SC", name: "South Carolina" },
      { code: "SD", name: "South Dakota" },
      { code: "TN", name: "Tennessee" },
      { code: "TX", name: "Texas" },
      { code: "UT", name: "Utah" },
      { code: "VT", name: "Vermont" },
      { code: "VA", name: "Virginia" },
      { code: "WA", name: "Washington" },
      { code: "WV", name: "West Virginia" },
      { code: "WI", name: "Wisconsin" },
      { code: "WY", name: "Wyoming" },
    ],
  },
  {
    name: "Mexico",
    iso: "MX",
    zipProvider: "zippopotam",
    states: [
      { code: "AGU", name: "Aguascalientes" },
      { code: "BCN", name: "Baja California" },
      { code: "BCS", name: "Baja California Sur" },
      { code: "CAM", name: "Campeche" },
      { code: "CHP", name: "Chiapas" },
      { code: "CHH", name: "Chihuahua" },
      { code: "CMX", name: "Ciudad de México" },
      { code: "COA", name: "Coahuila" },
      { code: "COL", name: "Colima" },
      { code: "DUR", name: "Durango" },
      { code: "GUA", name: "Guanajuato" },
      { code: "GRO", name: "Guerrero" },
      { code: "HID", name: "Hidalgo" },
      { code: "JAL", name: "Jalisco" },
      { code: "MEX", name: "Estado de México" },
      { code: "MIC", name: "Michoacán" },
      { code: "MOR", name: "Morelos" },
      { code: "NAY", name: "Nayarit" },
      { code: "NLE", name: "Nuevo León" },
      { code: "OAX", name: "Oaxaca" },
      { code: "PUE", name: "Puebla" },
      { code: "QUE", name: "Querétaro" },
      { code: "ROO", name: "Quintana Roo" },
      { code: "SLP", name: "San Luis Potosí" },
      { code: "SIN", name: "Sinaloa" },
      { code: "SON", name: "Sonora" },
      { code: "TAB", name: "Tabasco" },
      { code: "TAM", name: "Tamaulipas" },
      { code: "TLA", name: "Tlaxcala" },
      { code: "VER", name: "Veracruz" },
      { code: "YUC", name: "Yucatán" },
      { code: "ZAC", name: "Zacatecas" },
    ],
  },
  { name: "Afghanistan", iso: "AF" },
  { name: "Albania", iso: "AL" },
  { name: "Algeria", iso: "DZ" },
  { name: "Andorra", iso: "AD" },
  { name: "Angola", iso: "AO" },
  { name: "Antigua and Barbuda", iso: "AG" },
  { name: "Argentina", iso: "AR" },
  { name: "Armenia", iso: "AM" },
  { name: "Australia", iso: "AU" },
  { name: "Austria", iso: "AT" },
  { name: "Azerbaijan", iso: "AZ" },
  { name: "Bahamas", iso: "BS" },
  { name: "Bahrain", iso: "BH" },
  { name: "Bangladesh", iso: "BD" },
  { name: "Barbados", iso: "BB" },
  { name: "Belarus", iso: "BY" },
  { name: "Belgium", iso: "BE" },
  { name: "Belize", iso: "BZ" },
  { name: "Benin", iso: "BJ" },
  { name: "Bhutan", iso: "BT" },
  { name: "Bolivia", iso: "BO" },
  { name: "Bosnia and Herzegovina", iso: "BA" },
  { name: "Botswana", iso: "BW" },
  { name: "Brunei", iso: "BN" },
  { name: "Bulgaria", iso: "BG" },
  { name: "Burkina Faso", iso: "BF" },
  { name: "Burundi", iso: "BI" },
  { name: "Cabo Verde", iso: "CV" },
  { name: "Cambodia", iso: "KH" },
  { name: "Cameroon", iso: "CM" },
  { name: "Canada", iso: "CA" },
  { name: "Central African Republic", iso: "CF" },
  { name: "Chad", iso: "TD" },
  { name: "Chile", iso: "CL" },
  { name: "China", iso: "CN" },
  { name: "Colombia", iso: "CO" },
  { name: "Comoros", iso: "KM" },
  { name: "Congo", iso: "CG" },
  { name: "Costa Rica", iso: "CR" },
  { name: "Croatia", iso: "HR" },
  { name: "Cuba", iso: "CU" },
  { name: "Cyprus", iso: "CY" },
  { name: "Czech Republic", iso: "CZ" },
  { name: "Denmark", iso: "DK" },
  { name: "Djibouti", iso: "DJ" },
  { name: "Dominica", iso: "DM" },
  { name: "Dominican Republic", iso: "DO" },
  { name: "Ecuador", iso: "EC" },
  { name: "Egypt", iso: "EG" },
  { name: "El Salvador", iso: "SV" },
  { name: "Equatorial Guinea", iso: "GQ" },
  { name: "Eritrea", iso: "ER" },
  { name: "Estonia", iso: "EE" },
  { name: "Eswatini", iso: "SZ" },
  { name: "Ethiopia", iso: "ET" },
  { name: "Fiji", iso: "FJ" },
  { name: "Finland", iso: "FI" },
  { name: "France", iso: "FR" },
  { name: "Gabon", iso: "GA" },
  { name: "Gambia", iso: "GM" },
  { name: "Georgia", iso: "GE" },
  { name: "Germany", iso: "DE" },
  { name: "Ghana", iso: "GH" },
  { name: "Greece", iso: "GR" },
  { name: "Grenada", iso: "GD" },
  { name: "Guatemala", iso: "GT" },
  { name: "Guinea", iso: "GN" },
  { name: "Guinea-Bissau", iso: "GW" },
  { name: "Guyana", iso: "GY" },
  { name: "Haiti", iso: "HT" },
  { name: "Honduras", iso: "HN" },
  { name: "Hungary", iso: "HU" },
  { name: "Iceland", iso: "IS" },
  { name: "India", iso: "IN" },
  { name: "Indonesia", iso: "ID" },
  { name: "Iran", iso: "IR" },
  { name: "Iraq", iso: "IQ" },
  { name: "Ireland", iso: "IE" },
  { name: "Israel", iso: "IL" },
  { name: "Italy", iso: "IT" },
  { name: "Jamaica", iso: "JM" },
  { name: "Japan", iso: "JP" },
  { name: "Jordan", iso: "JO" },
  { name: "Kazakhstan", iso: "KZ" },
  { name: "Kenya", iso: "KE" },
  { name: "Kiribati", iso: "KI" },
  { name: "Kuwait", iso: "KW" },
  { name: "Kyrgyzstan", iso: "KG" },
  { name: "Laos", iso: "LA" },
  { name: "Latvia", iso: "LV" },
  { name: "Lebanon", iso: "LB" },
  { name: "Lesotho", iso: "LS" },
  { name: "Liberia", iso: "LR" },
  { name: "Libya", iso: "LY" },
  { name: "Liechtenstein", iso: "LI" },
  { name: "Lithuania", iso: "LT" },
  { name: "Luxembourg", iso: "LU" },
  { name: "Madagascar", iso: "MG" },
  { name: "Malawi", iso: "MW" },
  { name: "Malaysia", iso: "MY" },
  { name: "Maldives", iso: "MV" },
  { name: "Mali", iso: "ML" },
  { name: "Malta", iso: "MT" },
  { name: "Marshall Islands", iso: "MH" },
  { name: "Mauritania", iso: "MR" },
  { name: "Mauritius", iso: "MU" },
  { name: "Micronesia", iso: "FM" },
  { name: "Moldova", iso: "MD" },
  { name: "Monaco", iso: "MC" },
  { name: "Mongolia", iso: "MN" },
  { name: "Montenegro", iso: "ME" },
  { name: "Morocco", iso: "MA" },
  { name: "Mozambique", iso: "MZ" },
  { name: "Myanmar", iso: "MM" },
  { name: "Namibia", iso: "NA" },
  { name: "Nauru", iso: "NR" },
  { name: "Nepal", iso: "NP" },
  { name: "Netherlands", iso: "NL" },
  { name: "New Zealand", iso: "NZ" },
  { name: "Nicaragua", iso: "NI" },
  { name: "Niger", iso: "NE" },
  { name: "Nigeria", iso: "NG" },
  { name: "North Korea", iso: "KP" },
  { name: "North Macedonia", iso: "MK" },
  { name: "Norway", iso: "NO" },
  { name: "Oman", iso: "OM" },
  { name: "Pakistan", iso: "PK" },
  { name: "Palau", iso: "PW" },
  { name: "Palestine", iso: "PS" },
  { name: "Panama", iso: "PA" },
  { name: "Papua New Guinea", iso: "PG" },
  { name: "Paraguay", iso: "PY" },
  { name: "Peru", iso: "PE" },
  { name: "Philippines", iso: "PH" },
  { name: "Poland", iso: "PL" },
  { name: "Portugal", iso: "PT" },
  { name: "Qatar", iso: "QA" },
  { name: "Romania", iso: "RO" },
  { name: "Russia", iso: "RU" },
  { name: "Rwanda", iso: "RW" },
  { name: "Saint Kitts and Nevis", iso: "KN" },
  { name: "Saint Lucia", iso: "LC" },
  { name: "Saint Vincent and the Grenadines", iso: "VC" },
  { name: "Samoa", iso: "WS" },
  { name: "San Marino", iso: "SM" },
  { name: "Sao Tome and Principe", iso: "ST" },
  { name: "Saudi Arabia", iso: "SA" },
  { name: "Senegal", iso: "SN" },
  { name: "Serbia", iso: "RS" },
  { name: "Seychelles", iso: "SC" },
  { name: "Sierra Leone", iso: "SL" },
  { name: "Singapore", iso: "SG" },
  { name: "Slovakia", iso: "SK" },
  { name: "Slovenia", iso: "SI" },
  { name: "Solomon Islands", iso: "SB" },
  { name: "Somalia", iso: "SO" },
  { name: "South Africa", iso: "ZA" },
  { name: "South Korea", iso: "KR" },
  { name: "South Sudan", iso: "SS" },
  { name: "Spain", iso: "ES" },
  { name: "Sri Lanka", iso: "LK" },
  { name: "Sudan", iso: "SD" },
  { name: "Suriname", iso: "SR" },
  { name: "Sweden", iso: "SE" },
  { name: "Switzerland", iso: "CH" },
  { name: "Syria", iso: "SY" },
  { name: "Taiwan", iso: "TW" },
  { name: "Tajikistan", iso: "TJ" },
  { name: "Tanzania", iso: "TZ" },
  { name: "Thailand", iso: "TH" },
  { name: "Timor-Leste", iso: "TL" },
  { name: "Togo", iso: "TG" },
  { name: "Tonga", iso: "TO" },
  { name: "Trinidad and Tobago", iso: "TT" },
  { name: "Tunisia", iso: "TN" },
  { name: "Turkey", iso: "TR" },
  { name: "Turkmenistan", iso: "TM" },
  { name: "Tuvalu", iso: "TV" },
  { name: "Uganda", iso: "UG" },
  { name: "Ukraine", iso: "UA" },
  { name: "United Arab Emirates", iso: "AE" },
  { name: "United Kingdom", iso: "GB" },
  { name: "Uruguay", iso: "UY" },
  { name: "Uzbekistan", iso: "UZ" },
  { name: "Vanuatu", iso: "VU" },
  { name: "Vatican City", iso: "VA" },
  { name: "Venezuela", iso: "VE" },
  { name: "Vietnam", iso: "VN" },
  { name: "Yemen", iso: "YE" },
  { name: "Zambia", iso: "ZM" },
  { name: "Zimbabwe", iso: "ZW" },
]

/** Pinned-priority ISO codes, in display order: Brazil, Mexico, United States. */
const PRIORITY_ISO = ["BR", "MX", "US"] as const

/** Canonical, ordered country list: priority three first, then the rest alphabetical. */
export const COUNTRIES: Country[] = [
  ...PRIORITY_ISO.map((iso) => RAW_COUNTRIES.find((c) => c.iso === iso)!),
  ...RAW_COUNTRIES.filter((c) => !PRIORITY_ISO.includes(c.iso as (typeof PRIORITY_ISO)[number])).sort(
    (a, b) => a.name.localeCompare(b.name, "en"),
  ),
]

export const COUNTRY_NAMES: string[] = COUNTRIES.map((c) => c.name)

export const COUNTRY_BY_NAME: Record<string, Country> = Object.fromEntries(
  COUNTRIES.map((c) => [c.name, c]),
)

export const COUNTRY_BY_ISO: Record<string, Country> = Object.fromEntries(
  COUNTRIES.map((c) => [c.iso, c]),
)

export const STATES_BY_ISO: Record<string, { code: string; name: string }[]> = Object.fromEntries(
  COUNTRIES.map((c) => [c.iso, c.states ?? []]),
)
