import { z } from 'zod'
import { zodResolver } from '@hookform/resolvers/zod'
import { GENDERS } from './app-user.schema'

export const deceasedSchema = z.object({
  firstName:         z.string().min(1, 'Nome é obrigatório').max(100, 'Máximo 100 caracteres'),
  lastName:          z.string().min(1, 'Sobrenome é obrigatório').max(100, 'Máximo 100 caracteres'),
  gender:            z.enum(GENDERS).nullish(),
  birthDate:         z.string().nullish(),
  birthCity:         z.string().max(200).nullish(),
  birthState:        z.string().max(200).nullish(),
  birthCountry:      z.string().max(200).nullish(),
  deathDate:         z.string().nullish(),
  deathCause:        z.string().max(500).nullish(),
  deathCity:         z.string().max(200).nullish(),
  deathState:        z.string().max(200).nullish(),
  deathCountry:      z.string().max(200).nullish(),
  burialDate:        z.string().nullish(),
  burialLatitude:    z.number().nullish(),
  burialLongitude:   z.number().nullish(),
  burialSite:        z.string().max(300).nullish(),
  burialZip:         z.string().max(20).nullish(),
  burialStreet:      z.string().max(200).nullish(),
  burialNumber:      z.string().max(20).nullish(),
  burialComplement:  z.string().max(200).nullish(),
  burialNeighborhood: z.string().max(200).nullish(),
  burialCity:        z.string().max(200).nullish(),
  burialState:       z.string().max(200).nullish(),
  burialCountry:     z.string().max(200).nullish(),
  fb:                z.string().max(500).nullish(),
  instagram:         z.string().max(500).nullish(),
  linkedin:          z.string().max(500).nullish(),
  tiktok:            z.string().max(500).nullish(),
  x:                 z.string().max(500).nullish(),
  youtube:           z.string().max(500).nullish(),
  website:           z.string().max(500).nullish(),
  notes:             z.string().nullish(),
})

export type DeceasedFormValues = z.infer<typeof deceasedSchema>

export const deceasedResolver = zodResolver(deceasedSchema)

export const deceasedDefaultValues: DeceasedFormValues = {
  firstName:          '',
  lastName:           '',
  gender:             null,
  birthDate:          '',
  birthCity:          '',
  birthState:         '',
  birthCountry:       '',
  deathDate:          '',
  deathCause:         '',
  deathCity:          '',
  deathState:         '',
  deathCountry:       '',
  burialDate:         '',
  burialLatitude:     null,
  burialLongitude:    null,
  burialSite:         '',
  burialZip:          '',
  burialStreet:       '',
  burialNumber:       '',
  burialComplement:   '',
  burialNeighborhood: '',
  burialCity:         '',
  burialState:        '',
  burialCountry:      '',
  fb:                 '',
  instagram:          '',
  linkedin:           '',
  tiktok:             '',
  x:                  '',
  youtube:            '',
  website:            '',
  notes:              '',
}
